ory/hydra-maester

.goreleaser.yml

added go releaser yaml which will be later used in #6

Add goreleaser file

---

hydra/client.go
hydra/client_test.go

fix JSON decode bug

---

api/v1alpha1/oauth2client_types.go
config/crd/bases/hydra.ory.sh_oauth2clients.yaml
config/samples/hydra_v1alpha1_oauth2client.yaml
config/samples/hydra_v1alpha1_oauth2client_user_credentials.yaml
hydra/client_test.go
hydra/types.go

in some cases default client_secret_basic auth method is not suitable. 
Therefor it would be useful to expose token_endpoint_auth_method hydra API parameter to maester CRD

adding support for token_endpoint_auth_method

---

config/samples/hydra_v1alpha1_oauth2client_user_credentials.yaml

The hydra.ory.sh/v1alpha2 was never released. Let's keep the
sample at the proper apiVersion.

Fix sample apiVersion

---

controllers/oauth2client_controller.go

When the maester creates a client, it adds the namespace to the owner. This fix takes that into account when checking for updates.
Without this patch, the maester fails to update the client with hydra when the k8s admin makes changes to the oauth2client resource in a namespace.
Testing image is available at `dangersalad/hydra-maester:v0.0.12-alpha2`

fix(resolver): Fix client name detection for updates

---

Makefile
controllers/oauth2client_controller.go
controllers/oauth2client_controller_integration_test.go
main.go

alternative approach to #4. Modify SyncPeriod to control intervals between forced reconciliations for each CR.

feat: Sync mode - least work approach

---

controllers/oauth2client_controller.go
controllers/oauth2client_controller_integration_test.go
hydra/types.go

fix: Tolerate nil secret when tokenEndpointAuthMethod: none

---

api/v1alpha1/oauth2client_types.go
config/crd/bases/hydra.ory.sh_oauth2clients.yaml
hydra/types.go

Hi guys! 
As part of #36 
With these changes, we are now able to set the client's name through the OAuth2Client CRD.

feat: Adding oauth client name to the CRD spec

---

api/v1alpha1/oauth2client_types.go
api/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/hydra.ory.sh_oauth2clients.yaml
hydra/types.go

Allows `allowed_cors_origins` to be specified.

feat: Add AllowedCorsOrigins

---

.github/CODEOWNER
.github/FUNDING.yml
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/auto_assign.yml
.github/pull_request_template.md
.github/semantic.yml
.github/workflows/closed_references.yml
.github/workflows/labels.yml
.github/workflows/stale.yml
.reference-ignore
CODE_OF_CONDUCT.md
CONTRIBUTING.md
SECURITY.md

Updated repository templates to https://github.com/ory/meta/commit/ad9a6404080b7fb14d2d265ac0a2d4b685624d9b.

chore: update repository template to ad9a6404

---

.github/ISSUE_TEMPLATE/config.yml
CONTRIBUTING.md

Updated repository templates to https://github.com/ory/meta/commit/3ac3c4762144f1e12c6cefd62f8750794021e44d.

chore: update repository template to 3ac3c476

---

.github/ISSUE_TEMPLATE/config.yml
CONTRIBUTING.md

Updated repository templates to https://github.com/ory/meta/commit/39c4c3dbc588a2fc74d125f8ca37a88c79118b40.

chore: update repository template to 39c4c3db

---

.github/ISSUE_TEMPLATE/config.yml
CONTRIBUTING.md

Updated repository templates to https://github.com/ory/meta/commit/d066e55a5d42c40f34c31ef55d8eac1fdd3179c8.

chore: update repository template to d066e55a

---

.github/ISSUE_TEMPLATE/config.yml
CONTRIBUTING.md

Updated repository templates to https://github.com/ory/meta/commit/7f8a3988a0233d92f657afa65fcba96eae8a79e3.

chore: update repository template to 7f8a3988

---

.circleci/config.yml

Added anchor for installing kube builder and using links in the steps for it.
and signed the CLA.
vulnerability. If this pull request addresses a security vulnerability, I
confirm that I got green light (please contact
[security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
the changes.
works.
appropriate).

fix: installing kubebuilder binary.

---

.github/ISSUE_TEMPLATE/config.yml
CONTRIBUTING.md

Updated repository templates to https://github.com/ory/meta/commit/ed8a36281e6aeb1680630c97a66b691d04ed7457.

chore: update repository template to ed8a3628

---

.github/ISSUE_TEMPLATE/config.yml
.github/workflows/stale.yml
CONTRIBUTING.md

Updated repository templates to https://github.com/ory/meta/commit/e424c0a0a2dd85c585c0be32e8ada257c3fe8021.

chore: update repository template to e424c0a0

---

.github/ISSUE_TEMPLATE/config.yml
.github/config.yml
CONTRIBUTING.md

Updated repository templates to https://github.com/ory/meta/commit/ec210015daa04f26c81a639228ace6f6e8abaf11.

chore: update repository template to ec210015

---

.github/ISSUE_TEMPLATE/config.yml
.github/workflows/stale.yml
CONTRIBUTING.md

Updated repository templates to https://github.com/ory/meta/commit/455ef8896cd7ddfa08f4c2b8325c528bcdb65762.

chore: update repository template to 455ef889

---

.bin/.gitignore
.circleci/config.yml
.github/workflows/cve-scan.yaml
Dockerfile
Makefile
go.mod
go.sum

- Update golang to 1.16
- Import CVE checking pipeline
- Fixes https://github.com/ory/hydra-maester/issues/102
and signed the CLA.
introduces a new feature.
vulnerability. If this pull request addresses a security vulnerability, I
confirm that I got green light (please contact
[security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
the changes.
works.
appropriate).

chore: upgrade golang to 1.16

---

Dockerfile-kubebuilder
Makefile
api/v1alpha1/oauth2client_types.go
api/v1alpha1/oauth2client_types_test.go
config/crd/bases/hydra.ory.sh_oauth2clients.yaml
config/samples/hydra_v1alpha1_oauth2client.yaml

Expand validation and add tests for the following variations of responseTypes:
```
responseTypes:
- id_token
- code
- token
- code token
- code id_token
- id_token token
- code id_token token
```
- Fixes https://github.com/ory/hydra-maester/issues/101
and signed the CLA.
introduces a new feature.
vulnerability. If this pull request addresses a security vulnerability, I
confirm that I got green light (please contact
[security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
the changes.
works.
appropriate).

feat: support all variations of responseTypes

---

controllers/oauth2client_controller.go

This pull request introduces the ability to customize `ClientIDKey` and `ClientSecretKey` variables. These variables can now be modified by setting the environment variables `CLIENT_ID_KEY` and `CLIENT_SECRET_KEY` respectively. If these environment variables are not set, the default values (currently "CLIENT_ID" for `ClientIDKey` and "CLIENT_SECRET" for `ClientSecretKey`) will be used.
In this pull request, I have modified `ClientIDKey` and `ClientSecretKey` to be configurable via environment variables. This allows for greater flexibility in configuring the system, while maintaining sensible defaults.

feat: customize name of secret

---

hydra/client_test.go
hydra/types.go

Clients with a `BackChannelLogoutURI` or `FrontChannelLogoutURI` were not registered with such. More importantly, maester will remove the values during reconciliation. With this change, we enable to use the values regarding frontchannel and backchannel logout.
We already had the items in the CRD. However, these were not respected when creating or updating a client.
I consider this to be a bug. We provide the fields in the CRD. However they are not included in the HTTP requests against the API.
Reproduction:
```yaml
apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
name: frontend
spec:
grantTypes:
- client_credentials
responseTypes:
- id_token
- code
scope: 'openid'
secretName: oauth-client
backChannelLogoutURI: https://localhost/api/auth/logout/backchannel …
```

Implement creating clients with backchannel or frontchannel logout uris

---

api/v1alpha1/oauth2client_types.go
api/v1alpha1/oauth2client_types_test.go
api/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/hydra.ory.sh_oauth2clients.yaml
controllers/suite_test.go
hydra/types.go
hydra/types_test.go

Scopes are currently passed as a scope string, separating scopes by spaces.
Clients can grow to many scopes, resulting in a very long string.
This change allows us to specify scopes using the property scopeArray. That way, we can separate scopes by newlines.
Additionally, this allows us to comment a single scope temporarily or add a comment for a specific scope, e.g. as a reason why that client has this scope granted.
If this pull request addresses a security vulnerability, 
I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.

Allow scope to be passed as array

---

api/v1alpha1/oauth2client_types.go
api/v1alpha1/oauth2client_types_test.go
config/crd/bases/hydra.ory.sh_oauth2clients.yaml
controllers/oauth2client_controller.go
controllers/oauth2client_controller_integration_test.go

This new feature allows to disable hydra-maester OAuth2 client deletion. It can be a pitfall that, when a Kube CRD gets deleted, the OAuth2 client gets deleted too.
OAuth2 clients can be critical for production environments to work properly, and allowing to delete one when a Kubernetes CRD gets deleted has shown to be brittle for us. The CRDs are can be (temporarily) deleted for various reasons: human error, misconfiguration, etc.)
This feature should make hydra-maester safer.
No issue or design document - it's an implementation attempt of a feature that we would find useful on hydra-maester :)
If this pull request addresses a security vulnerability, 
I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.

feat: disable oauth2 client deletion

---

api/v1alpha1/oauth2client_types.go
api/v1alpha1/oauth2client_types_test.go
config/crd/bases/hydra.ory.sh_oauth2clients.yaml

- Increase the `maxLength` validation of `HydraAdmin.URL` from **64** to **256** characters in the CRD.  
- Regenerate the CRD schema automatically via `make manifests`.  
- Add a unit test to verify that a valid URL longer than 256 characters is rejected.
- A full URL (scheme `http(s)://`, port, path, query parameters, etc.) often exceeds 64 characters.  
- The previous limit of 64 likely originated from the maximum length of a DNS label (63), but it doesn’t apply to an entire URL.  
- 256 remains a reasonable cap to control Custom Resource size while covering the vast majority of real‑world URLs.
1. **Go code changes**  
- In `api/v1alpha1/oauth2client_types.go`, bump the `+kubebuilder:validation:MaxLength` tag to `256`.
2. **CRD regeneration**  
- Run `make manifests` to update …

chore: increase HydraAdmin.URL maxLength to 256 and add failing test for too-long URLs
